apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver-deploy
  name: webserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-deploy
  template:
    metadata:
      labels:
        app: webserver-deploy
    spec:
      containers:
      - image: 225110945643.dkr.ecr.us-east-1.amazonaws.com/bascher/phonebook-app:web
        name: webserver
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: mysql-secret
          - configMapRef:
              name: server-config    
        resources: {}
